# fly.toml app configuration file generated for swft on 2024-01-04T11:21:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "swft"
primary_region = "ewr"

[build]

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

